//Note: GUI generated from Netbeans

package tools;

public class MapEditorLauncher extends javax.swing.JFrame {
	private MapEditor editor;
	
    /**
     * Creates new form MapEditorLauncher
     */
    public MapEditorLauncher(MapEditor editor) {
    	this.editor = editor;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        newMapPanel = new javax.swing.JPanel();
        mapNameLabel = new javax.swing.JLabel();
        mapNameField = new javax.swing.JTextField();
        xLabel = new javax.swing.JLabel();
        xSpinner = new javax.swing.JSpinner();
        yLabel = new javax.swing.JLabel();
        ySpinner = new javax.swing.JSpinner();
        zName = new javax.swing.JLabel();
        zSpinner = new javax.swing.JSpinner();
        createMapButton = new javax.swing.JButton();
        existingMapPanel = new javax.swing.JPanel();
        existingMapField = new javax.swing.JTextField();
        fileExplorerButton = new javax.swing.JButton();
        loadMapButton = new javax.swing.JButton();

        fileChooser.setCurrentDirectory(new java.io.File("data\\maps"));
        fileChooser.setDialogTitle("Load Existing Map");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Genhat Map Editor");

        newMapPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("New Map"));

        mapNameLabel.setText("Map Name:");

        mapNameField.setToolTipText("The name of the new map.");

        xLabel.setText("x:");

        xSpinner.setModel(new javax.swing.SpinnerNumberModel(50, 1, 1000, 1));

        yLabel.setText("y:");

        ySpinner.setModel(new javax.swing.SpinnerNumberModel(50, 1, 1000, 1));

        zName.setText("z:");

        zSpinner.setModel(new javax.swing.SpinnerNumberModel(10, 1, 1000, 1));

        createMapButton.setText("Create Map");
        createMapButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createMapButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout newMapPanelLayout = new javax.swing.GroupLayout(newMapPanel);
        newMapPanel.setLayout(newMapPanelLayout);
        newMapPanelLayout.setHorizontalGroup(
            newMapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newMapPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newMapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(newMapPanelLayout.createSequentialGroup()
                        .addComponent(xLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(yLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(zName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newMapPanelLayout.createSequentialGroup()
                        .addComponent(mapNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mapNameField)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newMapPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createMapButton)
                .addContainerGap())
        );
        newMapPanelLayout.setVerticalGroup(
            newMapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newMapPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newMapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mapNameLabel)
                    .addComponent(mapNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newMapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xLabel)
                    .addComponent(xSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yLabel)
                    .addComponent(ySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zName)
                    .addComponent(zSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createMapButton)
                .addContainerGap())
        );

        existingMapPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Existing Map"));

        existingMapField.setText("data/maps/");

        fileExplorerButton.setText("...");
        fileExplorerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fileExplorerButtonMouseClicked(evt);
            }
        });

        loadMapButton.setText("Load Map");
        loadMapButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadMapButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout existingMapPanelLayout = new javax.swing.GroupLayout(existingMapPanel);
        existingMapPanel.setLayout(existingMapPanelLayout);
        existingMapPanelLayout.setHorizontalGroup(
            existingMapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(existingMapPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(existingMapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(existingMapPanelLayout.createSequentialGroup()
                        .addComponent(existingMapField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileExplorerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, existingMapPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(loadMapButton)))
                .addContainerGap())
        );
        existingMapPanelLayout.setVerticalGroup(
            existingMapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(existingMapPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(existingMapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(existingMapField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileExplorerButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadMapButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newMapPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(existingMapPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newMapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(existingMapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void createMapButtonMouseClicked(java.awt.event.MouseEvent evt) {                                             
        editor.createMap(mapNameField.getText(), (int)xSpinner.getValue(), (int)ySpinner.getValue(), (int)zSpinner.getValue());
    }                                            

    private void fileExplorerButtonMouseClicked(java.awt.event.MouseEvent evt) {                                                
        fileChooser.showOpenDialog(existingMapField);
        String filename = fileChooser.getSelectedFile().getPath();
        if (filename != null && !filename.isEmpty())
            existingMapField.setText(fileChooser.getSelectedFile().getPath());
    }                                               

    private void loadMapButtonMouseClicked(java.awt.event.MouseEvent evt) {                                           
        editor.loadMap(existingMapField.getText());
    }                                          

    // Variables declaration - do not modify                     
    private javax.swing.JButton createMapButton;
    private javax.swing.JTextField existingMapField;
    private javax.swing.JPanel existingMapPanel;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton fileExplorerButton;
    private javax.swing.JButton loadMapButton;
    private javax.swing.JTextField mapNameField;
    private javax.swing.JLabel mapNameLabel;
    private javax.swing.JPanel newMapPanel;
    private javax.swing.JLabel xLabel;
    private javax.swing.JSpinner xSpinner;
    private javax.swing.JLabel yLabel;
    private javax.swing.JSpinner ySpinner;
    private javax.swing.JLabel zName;
    private javax.swing.JSpinner zSpinner;
    // End of variables declaration                   
}
